### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmetals_decorations'!

### ISSUE THREAD

**Issue by zsdrN44** [Noaaan/MythicMetalsDecorations#22]
[14:07:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmetals_decorations'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:1.0.1]
Caused by: java.lang.NoSuchFieldError: MENDING
        at nourl.mythicmetalsdecorations.MythicMetalsDecorations.onInitialize(MythicMetalsDecorations.java:57) ~[%5B%E7%A5%9E%E8%AF%9D%E9%87%91%E5%B1%9E%E9%99%84%E5%B1%9E%5Dmythicmetals-decorations-0.6.0+1.20.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more

**Comment by Noaaan** [comment]
This is likely due to the Prometheum changes. For now you can downgrade Mythic Metals without any major issues, I will have this fixed today

**Comment by Noaaan** [comment]
Should be fixed already as of 0.6.1+
